### PR TITLE
Continue API (and 2 bug fixes)

### LINKED ISSUE #25: Use actual continue api for tile querying
Currently the tiles list for the query API doesn't take advantage of the continue mechanism that other query lists use. This will need to be fixed eventually.

### PR DESCRIPTION
**Pull request by elifoster**
There you go @retep998 

This closes #25 

I've already prepared 3.1.0, so when this gets merged it can immediately be ready for deploy to gamepedia.

### CODE REVIEW

File: api/TilesheetsQueryTranslationsApi.php [hunk 1]
```diff
@@ -45,10 +46,10 @@ public function execute() {
 
         $results = $dbr->select(
             'ext_tilesheet_languages',
-            array('display_name', 'description'),
+            '*',
             array(
                 'entry_id' => $id,
-                'lang' => $lang,
+                "lang = {$dbr->addQuotes($lang)} OR {$dbr->addQuotes($lang)} = ''",
```
Comment (Alexia) [inline api/TilesheetsQueryTranslationsApi.php]: Add quotes around the field name, is that intended?

Comment (retep998) [inline api/TilesheetsQueryTranslationsApi.php]: When using `'foo' => $bar` syntax it adds quotes and escapes it for you. When using `"foo = $bar"` I believe it doesn't do that, so you'd have to do it yourself.
